name: ci

on:
  push:
    branches:
      - "main"

env:
  REGISTRY_IMAGE: latenssi/phi-3-mini-4k-test

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: linux/amd64
            tag: amd64
            build-args: ""
          - platform: linux/arm64
            tag: l4t-cuda-11.4.14
            build-args: "BASE=nvcr.io/nvidia/l4t-cuda:11.4.14-runtime"
          - platform: linux/arm64
            tag: l4t-cuda-11.4.19
            build-args: "BASE=nvcr.io/nvidia/l4t-cuda:11.4.19-runtime"
          - platform: linux/arm64
            tag: l4t-cuda-12.2.12
            build-args: "BASE=nvcr.io/nvidia/l4t-cuda:12.2.12-runtime"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: ${{ matrix.platform }}
          tags: ${{ env.REGISTRY_IMAGE }}:${{ matrix.tag }}
          build-args: ${{ matrix.build-args }}
